services:
  home:
    build: ./microfrontend-store-home
    container_name: home
    ports:
      - "3001:3000"

  cart:
    build: ./microfrontend-store-cart
    container_name: cart
    ports:
      - "3002:3000"

  container:
    build: ./container
    container_name: container
    ports:
      - "3000:3000"
    depends_on:
      - home
      - cart
