services:
  home:
    build: ./microfrontend-store-home
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      NODE_ENV: production

  cart:
    build: ./microfrontend-store-cart
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      NODE_ENV: production

  container:
    build: ./container
    ports:
      - "3000:3000"
    depends_on:
      - home
      - cart